# This is a basic workflow to help you get started with Actions

name: CICD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Step 0 - Checkout main branch from GitHub
      - uses: actions/checkout@v2
      
      - name: Setup JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      
      # Step 1 - Increase the Patch part of the jar version 
      - name: Step 1 - Increase the Patch part of the jar version 
        run: echo Hello, world!
            
      # Step 2 - Compile the code
      - name: Step 2 - Compile the code
        run: mvn compile
        
      # Step 3 - Package it into an artifact
      - name: Step 3 - Package it into an artifact
        run: mvn -B package --file pom.xml
        
      # Step 4 - Create an artifact item for the build
      - name: Step 4 - Create an artifact item for the build
        run: ls -a
        
       # Step 5 - Create a docker image containing the artifact  
      - name: Step 5 - Create a docker image containing the artifact
        run: |
          cd target
          ls -a
        
       # Step 6 - Push the docker image to Docker Hub
      - name: Step 6 - Push the docker image to Docker Hub
        run: echo Hello, world!
        
       # Step 7 - Download and run the docker image
      - name: Step 7 - Download and run the docker image
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
